obj-$(CONFIG_QPNP_FG_MI8953)		+= qpnp-fg-mi8953.o
obj-$(CONFIG_QPNP_SMBCHARGER_MI8953)	+= qpnp-smbcharger-mi8953.o
obj-$(CONFIG_QPNP_FG_E7)		+= qpnp-fg_e7.o
obj-$(CONFIG_QPNP_SMBCHARGER_E7)	+= qpnp-smbcharger_e7.o